
server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 1m



#thread pool
async:
  executor:
    thread:
      corePoolSize: 10
      maxPoolSize: 30
      queueCapacity: 5000
      name:
        prefix: async-service-
